# Generated by Django 5.2.7 on 2025-11-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('services', 'Services'), ('training', 'Training'), ('technical', 'Technical'), ('pricing', 'Pricing')], default='services', max_length=50),
        ),
    ]
